### ISSUE TITLE
feature: modify fold icons

### ISSUE THREAD

**Issue by petobens** [stevearc/aerial.nvim#257]
### Neovim version (nvim -v)

Latest Master

### Operating system/version

Arch Linux

### Output of :AerialInfo

-

### Describe the bug

Currently fold icons,   `  SELECTED` glyph, seem to be hardcoded as in the image (or at least I didn't find a way to modify them).
I was wondering whether you could introduce a config option to make them configurable?

![image](https://github.com/stevearc/aerial.nvim/assets/2583971/ded510a3-7852-42a6-9467-fe671ff2b45f)

### Steps To Reproduce

-

### Expected Behavior

-

### Minimal example file

-

### Minimal init.lua

```Lua
-
```

**Comment by stevearc** [comment]
Check the documentation for the `icons` config option. You can used `Collapsed` to set the default icon, and you can set specific icons for each collapsed symbol with `<Symbol>Collapsed`

**Comment by petobens** [comment]
Thanks! Can I change the highlight group only for the default `Collapsed` icon (i use `>`)?  There doesn't seem to be a specific highlight group for this since it seems to link to the underlying symbol? i.e if for instance I've folded a function I see:
```
AerialFunctionIcon links to Function aerial
```

**Comment by stevearc** [comment]
You can customize those highlights using the `get_highlight` config function. For example:
```lua
require("aerial").setup({
    get_highlight = function(symbol, is_icon, is_collapsed)
      if is_icon and is_collapsed then
        return "Comment"
      end
    end,
})
```

**Comment by petobens** [comment]
Great! thanks :)

**Comment by petobens** [comment]
Is it possible to show the symbol icon instead of the collapsed icon whenever there is a terminal/end fold? 

For instance in the next gif once I open the `telescope_filter` fold, the `opts.attach_mappings` function has a `>` symbol indicating it is `Collapsed`. However there is anything to actually fold here (pressing `zo` neither opens the fold nor changes  the fold icon). I would like in this case to show the function symbols icon rather than the collapsed one (since we've reached a "terminal/end" fold). 

(I can open a new issue if you deem fit).

![aerial_fold](https://github.com/stevearc/aerial.nvim/assets/2583971/7d63f9f8-5bf3-4058-8275-07ccf5eca2b5)

**Comment by stevearc** [comment]
The reason leaf nodes can even become collapsed is because it can be linked to code folding. It has been the case that if `manage_folds = false` the leaf nodes cannot be collapsed. I've just pushed a change that makes it such that if `link_tree_to_folds = false` it will also prevent leaf nodes from being collapsed.

**Comment by petobens** [comment]
Mmm I added a `link_tree_to_folds = false,` to my config but I'm still seeing the behaviour above. Do I need to set an extra option?

**Comment by stevearc** [comment]
You'll need to update to the latest version. I meant to tag this issue in 79ebaf01eb57fbf56e4291332e4e2a927cbb1162 but I typo'd the issue number

**Comment by stevearc** [comment]
Wait no nvm that was for a different issue. 5c5b355f29664577738d8843e948d16ff17afe65 was tagged, just make sure you've updated past that

**Comment by petobens** [comment]
Yep I did update. I'll try to cook a minimal reproducible example over the weekend (essentially if open the aerial buffer, i run the acction `tree_close_all` and then try to open a fold then the leaf has the fold icon instead of the symbol as in my GIF)

**Comment by petobens** [comment]
So if I use the following minimal.lua:
```lua
local root = '/tmp/nvim-minimal'

-- Set stdpaths to use root dir
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
    vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- Bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        'git',
        'clone',
        '--filter=blob:none',
        '--single-branch',
        'https://github.com/folke/lazy.nvim.git',
        lazypath,
    })
end
vim.opt.runtimepath:prepend(lazypath)

-- Install plugins
local plugins = {
    {
        'nvim-treesitter/nvim-treesitter',
        build = ':TSUpdate',
        config = function()
            require('nvim-treesitter.configs').setup({
                ensure_installed = {
                    'lua',
                },
                highlight = {
                    enable = true,
                },
            })
        end,
    },
    { 'folke/tokyonight.nvim' },
    {
        'stevearc/aerial.nvim',
        config = function()
            require('aerial').setup({
                layout = {
                    width = 43,
                    default_direction = 'left',
                    placement = 'edge',
                    preserve_equality = true,
                },
                close_on_select = true,
                highlight_on_hover = true,
                highlight_on_jump = 500,
                icons = {
                    Collapsed = '>',
                },
                link_tree_to_folds = false,
                get_highlight = function(_, is_icon, is_collapsed)
                    if is_icon and is_collapsed then
                        return 'Comment'
                    end
                end,
                keymaps = {
                    ['v'] = 'actions.jump_vsplit',
                    ['s'] = 'actions.jump_split',
                    ['zm'] = 'actions.tree_close_all',
                    ['zr'] = 'actions.tree_open_all',
                },
            })
        end,
    },
}
require('lazy').setup(plugins, {
    root = root .. '/plugins',
})

vim.cmd.colorscheme('tokyonight')
```
and, as in the GIF, I open nvim and run `:AerialOpen` I see that the `get_highlight` function shows the fold `>` icon rather than the `[F]` function leaf icon. 

![fold2](https://github.com/stevearc/aerial.nvim/assets/2583971/cbf0cd54-d837-4d42-acf2-0ecf215d3245)

**Comment by stevearc** [comment]
Well...I don't know what to tell you. I ran the repro with `nvim -u repro.lua repro.lua` and after a single restart this is what it looks like.

![image](https://github.com/stevearc/aerial.nvim/assets/506791/eafd3abf-8252-4c2a-844a-7e2de7ca8a33)

I can't find a way for it to show a collapsed icon for a leaf node

**Comment by petobens** [comment]
Ohh I see what's going on:
1. I open aerial with `:AerialOpen`
2. I close all folds with my `zm` mapping which runs `actions.tree_close_all`
3. I open the config fold with `zo` mapping which runs `actions.tree_open` and correctly opens the `config` node but not `get_config`.
4. I run again `zo` on `get_highlight` but nothing happens. If I run `zr` (`actions.tree_open_all`) then `get_highlight` indeed gets open.

So I guess the behaviour I expect is that the `zo` mapping on a parent node also triggers a leaf node open if the child node/leaf is indeed a terminal node?  I understand however that the current behaviour might be a feature rather than a bug and you can happily ignore my comment.
