### ISSUE TITLE
[Lua] Files with local and global scoped functions not displaying as expected

### ISSUE THREAD

**Issue by olimorris** [stevearc/aerial.nvim#51]
**Describe the bug**
I've noticed that when I have a `lua` file which has a mixture of `local` and `global` functions, Aerial only displays the `local` ones. Yet when I have a file of just `global` functions, it displays them as expected.

**System information**
- OS: mac
- Neovim version: 0.6.1
- AerialInfo:
```bash
Filetype: lua
Configured backends:
  lsp (not supported) [LSP client not attached (did you call aerial.on_attach?)]
  treesitter (supported) (attached)
  markdown (not supported) [Filetype is not markdown]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct
```
- Aerial config:
```lua
aerial.setup({
  close_on_select = true,
  default_direction = "prefer_right",
  min_width = 40
})
```

**To Reproduce**
1. Load [functions.lua](https://github.com/olimorris/dotfiles/blob/main/.config/nvim/lua/Oli/core/functions.lua) in Neovim, open Aerial and observe all functions working as expected
2. Load [utils.lua](https://github.com/olimorris/dotfiles/blob/main/.config/nvim/lua/Oli/core/utils.lua) in Neovim, open Aerial and observe that only `local` functions are displayed

**Screenshots**

_functions.lua_
![Screen Shot 2022-01-26 at 09 14 05@2x](https://user-images.githubusercontent.com/9512444/151135380-4135e831-02c9-464c-87d9-bf74d77fc609.png)

_utils.lua_
![Screen Shot 2022-01-26 at 09 13 02@2x](https://user-images.githubusercontent.com/9512444/151135228-4f1aaa9a-a6ad-497c-8e67-e58b151a9da9.png)

**Comment by stevearc** [comment]
Should be fixed now. Thanks for the report!

**Comment by tristone13th** [comment]
> Should be fixed now. Thanks for the report!

I'm using the same configuration and latest version, it seems this problem still appears...

**Comment by stevearc** [comment]
@tristone13th could you provide a code snippet of a function that does not appear?

**Comment by tristone13th** [comment]
> 

<img width="902" alt="image" src="https://user-images.githubusercontent.com/17382962/159819099-fc52c0f9-6b14-4629-af31-f78175de87af.png">

For example ,the "symbols" and "lastplace" function didn't show up in the list.

**Comment by stevearc** [comment]
Should be fixed

**Comment by tristone13th** [comment]
> Should be fixed

Thanks for your instant fix, keep on your great work!
